language: node_js
node_js:
  - 6
install:
  - npm install -g travis-ci-cloudfront-invalidation
script:
  - mkdir .generated
  - cp static/* .generated
  - sed "s/{date}/`date +%Y-%m-%d`/" templates/sitemap.xml > .generated/sitemap.xml
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: alexeydonov.net
  region: eu-west-1
  skip_cleanup: true
  local_dir: .generated
  detect_encoding: true
  default_text_charset: 'utf-8'
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_ACCESS_KEY -c $CF_DISTRIBUTION_ID -i "/*" -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,stage'
