services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./generated:/var/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./ssl:/etc/ssl
    restart: unless-stopped
